name: CD - Deploy Prometheus Stack

on:
  workflow_run:
    workflows: ["CD - Associate VPN and Deploy to EKS"]
    types:
      - completed

jobs:
  cd-prometheus:
    # workflow_run 트리거 자체가 CI 성공 후 실행을 보장하므로 needs는 불필요합니다.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          repository: CLD-3rd/Final-Team3-manifests
          token: ${{ secrets.GH_TOKEN }}
          ref: feat/app
          path: manifest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name matchfit-eks \
            --region ap-northeast-2

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add & Update Helm repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Deploy Prometheus stack
        run: |
          helm upgrade --install prom-stack prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace \
            --values manifest/base/monitoring/values.yaml

